### ISSUE TITLE
MountUp compatibility issue

### ISSUE THREAD

**Issue by PepijnMC** [PepijnMC/ElevationDragRuler#17]
**Describe the bug**
From #16 

> Having this addon enabled alongside [Mount Up](https://github.com/p4535992/MountUp) causes the Mount Up button to disappear.

**Comment by PepijnMC** [comment]
I have tried to reproduce the issue with all 4 possible locations of the MountUp button but everything shows up fine.
![Screenshot_1](https://user-images.githubusercontent.com/13134303/161542708-9f201f6a-1ce2-4e04-a733-66531fc11e4e.png)

**Comment by DivertedCircle** [comment]
Your mention of moving the MountUp button has made me realize I'm not evening seeing MountUp as an option in the module settings menu. I'll need to troubleshoot that, I suspect the module isn't working at all and there isn't a compatibility issue.

**Comment by PepijnMC** [comment]
Alright, thank you for confirming! I will close this for now.
