### ISSUE TITLE
Add support for standing up from prone.

### ISSUE THREAD

**Issue by PepijnMC** [PepijnMC/ElevationDragRuler#26]
The prone condition can be ended by a creature if they spend half of their movement speed to stand up, if movement history is on this movement reduction should be automatically applied for the current round.

**Note**
This 5e rule was not written with multiple movement speeds in mind. Normally if a rule refers to your movement speed it means all your movement speeds, but spending movement speed is handled in such a way that this ruling wouldn't make much sense.
In 5e you calculate your remaining speed for any movement option by subtracting how far you have already moved from its maximum. So if you have a 30ft walking speed and a 60ft flying speed, walking for 20ft means your remaining walking speed is 30-20=10ft and your remaining flying speed is 60-20=40ft. Spending half of each movement speed to stand up makes this inconsistent, you would have spent different amounts of movement.
Crawford has commented on this and states the more logical ruling is to spend half of your maximum speed, which is what I will likely implement.

**Comment by PepijnMC** [comment]
It was tedious but I got it to work in what I think is a reasonable manner. At the start of every combat turn the module will check if the token has the prone condition and save that info to the `wasProne` flag. Once the token starts being dragged the module will once again look for the prone condition. If the prone condition is no longer active but `wasProne` is true, the module will know that the token has stood up and subtract the appropriate amount from your initial available speed (this does not affect dashing). By default this is half of your highest movement speed, but this can be configured in the Resource tab of the token config (since there are features like Athlete which reduce the cost to a flat 5ft.).

This does mean that applying and removing the prone condition during the same exact turn will not count, this is helpful when you add the prone condition by mistake but it does mean actually going prone on your turn and standing up will not be detected. For these cases you can still manually set the `wasProne` flag with a simple macro, this flag properly resets itself the next turn (and on scene switching to make sure it doesn't linger, although I might do this when combat ends instead).

**Comment by KristjanLaane** [comment]
This is fantastic!

> For these cases you can still manually set the wasProne flag with a simple macro
How do you set that, what is the line of code?
