### ISSUE TITLE
Features request: moving through another token should be difficult terrain

### ISSUE THREAD

**Issue by cs96and** [PepijnMC/ElevationDragRuler#29]
Moving through another token should be classed as difficult terrain.  There may be the odd exception where this is not the case (e.g. air elemental moving through another character's space), but it is true most of the time.

**Describe the solution you'd like**
An option to treat other tokens' spaces as difficult terrain

**Comment by PepijnMC** [comment]
Enhanced Terrain Layer already supports tokens causing difficult terrain.
