### ISSUE TITLE
Compatibilidade com Metric Ruler Labels

### ISSUE THREAD

**Issue by rinnocenti** [PepijnMC/ElevationDragRuler#38]
without much to put, but it can be compatible with the module:
https://github.com/Roger92/metric-ruler-labels

**Comment by PepijnMC** [comment]
This module is built on top of Drag Ruler, which is already supported by Metric Ruler. There are as far as I know no compatibility issues introduced by my module.
![Screenshot_1](https://user-images.githubusercontent.com/13134303/201486225-9073b60e-c35b-4eb2-ab2b-c2c87a1ec143.png)
