### ISSUE TITLE
chenge elevation does not always mean being in another type of movement

### ISSUE THREAD

**Issue by rinnocenti** [PepijnMC/ElevationDragRuler#4]
The module is very cool, but there is a problem with it in use.
changing the character's elevation doesn't always mean he's flying or digging. sometimes it's just on a different level.
It would be nice to have a button to change the type of movement instead of just forcing the movement based on its elevation.

The urban mode not work as well

**Comment by PepijnMC** [comment]
As stated in the README you can use Urban terrain from Enhanced Terrain Layer to disable elevation-based movement changing. I agree this isn't ideal but it will have to do for the time being, a dedicated button is unfortunately a bit out of scope for now as this is simply a speed provider for Drag Ruler.

**Comment by rinnocenti** [comment]
it needs to start the movement within the urban terrain, which means that in these terranos it will not be possible to use other movements only the largest one.
