### ISSUE TITLE
Two errors

### ISSUE THREAD

**Issue by shecrio** [PepijnMC/ElevationDragRuler#40]
Foundry v10.290
Dnd5e v2.0.3
Drag Ruler v1.13.2
5e Integration v1.8.5
Routinglib v1.0.6

Two errors, neither are present if I disable DnD5e Drag Ruler Integration

When dragging a token it does not color the path per Drag Ruler and throws this error

api.js:99 TypeError: Cannot read properties of undefined (reading 'length')
    at util.js:117
    at Array.forEach (<anonymous>)
    at getMovementTotal (util.js:115)
    at DnD5eSpeedProvider.getRanges (speed_provider.js:24)
    at getRangesFromSpeedProvider (api.js:90)
    at DragRulerRuler.dragRulerGetColorForDistance (ruler.js:468)
    at DragRulerRuler.highlightMeasurementNative (foundry_imports.js:212)
    at DragRulerRuler.performPostPathfindingActions (ruler.js:187)
    at ruler.js:128
getRangesFromSpeedProvider @ api.js:99
dragRulerGetColorForDistance @ ruler.js:468
highlightMeasurementNative @ foundry_imports.js:212
performPostPathfindingActions @ ruler.js:187
(anonymous) @ ruler.js:128
Promise.then (async)
measure @ ruler.js:124
scheduleMeasurement @ foundry_imports.js:153
onMouseMove @ foundry_imports.js:145
onEntityLeftDragMove @ main.js:159
onEntityLeftDragMoveSnap @ main.js:153
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁Token.prototype._onDragLeftMove#0 @ libWrapper-wrapper.js:189
callback @ foundry.js:27723
_handleDragMove @ foundry.js:28080
_handleMouseMove @ foundry.js:28052
a.emit @ index.js:202
r.dispatchEvent @ interaction.min.mjs:8
r.processPointerMove @ interaction.min.mjs:8
t.recursiveFindHit @ interaction.min.mjs:8
t.findHit @ interaction.min.mjs:8
r.processInteractive @ interaction.min.mjs:8
r.onPointerMove @ interaction.min.mjs:8

When trying to Clear Movement History I get this error

main.js:57 Uncaught ReferenceError: resetMovementHistory is not defined
[Detected 1 package: elevation-drag-ruler]
    at Object.menu.<computed>.callback (main.js:57)
    at ContextMenu.#onClickItem (foundry.js:55897)
    at HTMLElement.dispatch (jquery.min.js:2)
    at HTMLElement.y.handle (jquery.min.js:2)
menu.<computed>.callback @ main.js:57
#onClickItem @ foundry.js:55897
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

**Comment by shecrio** [comment]
adding Enhanced Terrain Layer and Terrain Ruler fixes the first issue but not the second

**Comment by PepijnMC** [comment]
Should be fixed in v1.8.6
