### ISSUE TITLE
Tokens hidden from players can cause difficult terrain

### ISSUE THREAD

**Issue by R0TEAM** [PepijnMC/ElevationDragRuler#56]
First - i dont know which "drag ruler related" module this problem realy create ...
I have drag ruler/drag ruler DnD5 integration/Enhanced terrain Layer and terrain Ruler (all Latest versions - foundry latest Stable version)

If i drag an hero over an enemy Token (live or dead) - the numer of the distance swap to "infinity" and Red .... and the player cant execute this movement ....
I "think" it can be this modul (as DnD rules forbiden movement over an enemy creature) - but i dont know sure ...
This is an bigger problem as i have first thinked ...
As the player can try drag around his token and see then on the change of the color is an enemy hidden creature around him ...
(not to say, that this should not block movement over dead enemy tokens .... ......)
If this an new addition then i would suggest an switch - as it is so many conditions where an player "can" move over an enemy ... i would this self decide as GM .....
If your module is not the culprit ... sorry .... feel free do forward it to the right drag related module - i cant narrow it down
(sorry is my english bad - it is not my first language)

**Comment by PepijnMC** [comment]
Tokens causing difficult terrain is a setting from Enhanced Terrain Layer, you can turn it off in there. This module merely implements the dnd5e rules for moving through other creatures, which includes not being able to move through hostile creatures of equal size.

I will see what I can do about hidden tokens however, it isn't great they can be detected by just dragging the ruler around a bunch.

**Comment by R0TEAM** [comment]
Thanks for you answer ;)
and would be nice to get no player dedectable hiden token :D
I know the setting that Tokens causing difficult terrain ...
but the problem is that dead enemy tokens block movement too, it should only behavor like non enemy tokens .... i dont know if it dedectable ingame if the token is "dead" ....
