### ISSUE TITLE
Drag Ruler shows no difference movement required to move through tokens with Terrain Ruler etc.

### ISSUE THREAD

**Issue by Krigsmaskine** [PepijnMC/ElevationDragRuler#58]
**Describe the bug**
When Enhanced Terrain Layer gets its' rule provider from DnD5e Drag Ruler Integration, this seemingly does nothing at all. In older versions of Drag Ruler, it showed infinity, which was actually why I posted the bug here, but after updating, it just doesn't seem to do anything. Is this intentional? Unsure if you're the one showing the option of DnD5e Drag Ruler Integration in the Enhanced Terrain Layer or if it's the other way around. Works if you change it to built-in, so maybe it just shouldn't auto select the integration module?

**To Reproduce**
1. Toggle on the include options in Enhanced Terrain Layer.
2. Have the rule provider be DnD5e Drag Ruler Integration.
3. Drag over token(s) you've allowed in the include options.
4. See no change in the distance dragged at all, regardless of what you've chosen.

**Screenshots**
![image](https://user-images.githubusercontent.com/39592771/229319939-8233b7fc-b17e-4dc1-818f-731e61afdfd0.png)
![image](https://user-images.githubusercontent.com/39592771/229319955-3e5f6b2d-c201-4007-9109-624677418f0f.png)

**Comment by PepijnMC** [comment]
A reload (F5) is required after changing any of the 'Include Tokens' settings from Enhanced Terrain Layer.

**Comment by Krigsmaskine** [comment]
Chatted on Discord too, a reload solves it.
