### ISSUE TITLE
Movement speed for groups isn't working

### ISSUE THREAD

**Issue by dkniffin** [PepijnMC/ElevationDragRuler#60]
**Describe the bug**
I noticed [group speed is supported](https://github.com/PepijnMC/ElevationDragRuler/blob/e17bb4232bbb4e73ba02759daa099f89cf4d4160/scripts/speed_provider.js#L36-L40). However, it's not working in my game.

**To Reproduce**
1. Create a group actor with a movement speed
2. Drag the token on a map

**Expected behavior**
The token's movement speed should be colored correctly.

**Screenshots**

![Screen Shot 2023-05-31 at 10 55 57 PM](https://github.com/PepijnMC/ElevationDragRuler/assets/1680080/da3598c8-44a6-4090-bc64-dc7c45c8af86)
![Screen Shot 2023-05-31 at 10 57 03 PM](https://github.com/PepijnMC/ElevationDragRuler/assets/1680080/887b8ffa-fb61-42d2-82e8-335ee234cb03)

**Additional context**
From what I can see, the data needed is in `token.document.actor.system.attributes.movement`, even for group tokens.

**Comment by PepijnMC** [comment]
Thank you, the system must have changed it at some point. Fixed in 1.9.4.
