### ISSUE TITLE
Movement remains after token is done

### ISSUE THREAD

**Issue by Liviu50** [PepijnMC/ElevationDragRuler#62]
So the main way of reproducing is simply to activate the module and drag your token.
For you, nothing weird but for others the last "movement" remains on map and does not go away.

Ideally it should not  do this, as once the movement has been done it should simply delete any waypoint or ruler on the map...but it stays on the map until you move your token again.

![image](https://github.com/PepijnMC/ElevationDragRuler/assets/96814785/36cb0d6a-25ee-4bf7-8f2e-9db10fcd6a09)

I have plenty of modules but this is the first time it leaves marks like this, anyone had something siimilar happening?

**Comment by Liviu50** [comment]
ah just remembered: if you change map and go back to where the marks are, they disappear.

**Comment by PepijnMC** [comment]
I cannot replicate this given the provided method. Can you replicate your issue with just the the module and its dependencies enabled?

**Comment by Liviu50** [comment]
i will try, do you think its another module the issue?

**Comment by Liviu50** [comment]
Ok so i tried disabling EVERYTHING (except socketlib ofc) 
issue persists. 
when someone else (not me) drags a character the "range" color and distance is saved and does not go away until you move it again or refresh the page (or go another page and come back)

**Comment by PepijnMC** [comment]
I cannot reproduce the issue using FoundryVTT 11.302 (Standalone and Chrome), Drag Ruler 1.13.8, DnD5e Drag Ruler Integration 1.10.0, and socketlib 1.0.13. I unfortunately cannot fix something I can't reproduce, but please also make sure this is not an issue you are experiencing with just Drag Ruler.

**Comment by grimmlock** [comment]
Known issue with Drag Ruler, appears to be a Foundry bug, and has been reported [here](https://github.com/manuelVo/foundryvtt-drag-ruler/issues/285) along with a temporary fix.

**Comment by Liviu50** [comment]
cheers mate, do you think it will be solved by the module? 
Also ill close this ticket :) still please answer my questions i would love to have it fix permanently since i use this module 100% of the time.
Thx for letting me know! :)
