### ISSUE TITLE
[Bug] Conflict with Terrain Mapper

### ISSUE THREAD

**Issue by GhostwheelX** [PepijnMC/ElevationDragRuler#65]
After installing the [Terrain Mapper](https://github.com/caewok/fvtt-terrain-mapper) module, I'm getting the following error:

![image](https://github.com/PepijnMC/ElevationDragRuler/assets/68725723/59978c98-fd52-4451-8b55-0297d3d66bb7)

I'm not sure which error would give more information since I've got quite a few of them, but here are some that seem like they might be relevant:

![image](https://github.com/PepijnMC/ElevationDragRuler/assets/68725723/760f007f-3ab2-4a30-904b-d33ced5fdad7)
![image](https://github.com/PepijnMC/ElevationDragRuler/assets/68725723/81832e87-d39f-4b26-9c9b-a8993b82dd3e)
![image](https://github.com/PepijnMC/ElevationDragRuler/assets/68725723/d397a5e2-f11d-45f7-b1ff-fd9854071e35)
![image](https://github.com/PepijnMC/ElevationDragRuler/assets/68725723/420cfa37-15f5-4f8d-86a4-acdca1bc0f36)

Any idea what might be causing this? Thanks!

**Comment by caewok** [comment]
Terrain Mapper uses `canvas.terrain` as a layer. I would guess that Elevation Drag Ruler expects `canvas.terrain` to point to something added by a different module---probably Enhanced Terrain Layer? If I am right, a simple fix would be to check for Enhanced Terrain Layer and if not present, don't try to wrap that (nonexistent) method or reference those ETL objects.

**Comment by PepijnMC** [comment]
Modules work fine together with only them and their dependencies enabled, I already check if modules are active. You might have either Enhanced Terrain Layer or Terrain Ruler active, best to disable them both as do no longer do anything in the latest version.
