### ISSUE TITLE
[Feature Request] Automatically enable pathfinding

### ISSUE THREAD

**Issue by GhostwheelX** [PepijnMC/ElevationDragRuler#69]
Might there be a way to add an option to the settings of the module that automatically sets pathfinding for all players by default, maybe even disabling the button if the GM wants it to be hidden from players?

**Comment by PepijnMC** [comment]
Same as other request, this is something to implement in[ Drag Ruler](https://github.com/manuelVo/foundryvtt-drag-ruler/tree/master) itself.
