### ISSUE TITLE
Add settings to ignore movement costs from certain terrains depending on your movement speed.

### ISSUE THREAD

**Issue by PepijnMC** [PepijnMC/ElevationDragRuler#7]
Currently common sense dictates when a movement speed should ignore a certain type of difficult terrain. It would be cool to make this customizable.

**Comment by XtraButtery** [comment]
Would this also include the ability to set flags to actors to ignore types of difficult terrain based on certain flags being set?
This would be useful for the Ranger class, various magic items which allow the wearer to ignore terrain, and the Earth Genasi off the top of my head.

The API for Enhanced Terrain Layer seems to support this, but none of the drag rulers appear to have implemented it.

**Comment by PepijnMC** [comment]
Although related I don't think I will implement both simultaneously so I made a separate issue. I personally do not use Foundry's character sheets in any of my games so I will have to look into their API.
