### ISSUE TITLE
[Feature Request] Right click to set waypoints

### ISSUE THREAD

**Issue by GhostwheelX** [PepijnMC/ElevationDragRuler#70]
I know this has been mentioned on the Discord server, but I wanted to be notified when it was live so I figured I would add an issue.

Would it be possible to add an option to right-click while dragging a token to set a waypoint during movement?

**Comment by PepijnMC** [comment]
That would be something to implement in the [Drag Ruler](https://github.com/manuelVo/foundryvtt-drag-ruler/tree/master) module itself.
