### ISSUE TITLE
token movement failures with foundry V12 release

### ISSUE THREAD

**Issue by bagoldendick** [PepijnMC/ElevationDragRuler#71]
**Describe the bug**
When Foundry Released V12 Stable... it broke drag ruler.

**To Reproduce**
Attempt to move any token while drag ruler is installed and having updated the server to V12 Stable Build

**Expected behavior**
Re-implementation of a phenomenal that makes my players and fellow DMs extremely happy.
![DragRuler_1](https://github.com/user-attachments/assets/51c9fe0c-c536-4085-9f51-d8c89ae1f079)

**Screenshots**

**Additional context**

**Comment by PepijnMC** [comment]
[Drag Ruler](https://github.com/manuelVo/foundryvtt-drag-ruler) has not been updated to v12. This is the github for the 5e integration module, I cannot fix issues with the main Drag Ruler module.
