### ISSUE TITLE
Drag-Ruler doesn't seem to be picking up Diagonal settings from Core 4.0

### ISSUE THREAD

**Issue by Liwnori** [PepijnMC/ElevationDragRuler#74]
**Describe the bug**
When configured for Alternating (1/2/1) in the core settings, drag-ruler is only calculating movement for diagonals at Equidistant (1)

**To Reproduce**
Settings in Screenshots

**Expected behavior**
Moving 2 diagonals should equal 15 and not 10
Moving 4 should equal 30, not 20

**Screenshots**
![image](https://github.com/user-attachments/assets/f8ea0e54-7333-4459-93cd-bcf9cd0ebc59)
![image](https://github.com/user-attachments/assets/e5505a41-89ae-4f06-a3e5-a45f8d928948)
![image](https://github.com/user-attachments/assets/bb7681df-a00f-4317-aece-daae3f4ce60b)

**Additional context**
Currently running latest Foundry v12, and latest DnD 5e (4.0.4)

**Comment by PepijnMC** [comment]
This page is not for the Drag Ruler module. See https://github.com/manuelVo/foundryvtt-drag-ruler

**Comment by Liwnori** [comment]
> This page is not for the Drag Ruler module. See https://github.com/manuelVo/foundryvtt-drag-ruler
Thanks, my mistake.
