### ISSUE TITLE
Error in token HUD

### ISSUE THREAD

**Issue by rinnocenti** [PepijnMC/ElevationDragRuler#8]
![image](https://user-images.githubusercontent.com/3178127/152601139-8f22781b-34fa-403c-8455-c4e6c3db5400.png)

when opening the hud token you get this error and no button appears

**Comment by PepijnMC** [comment]
Could you make sure the issue can be reproduced with all other modules (except drag ruler and socketlib) disabled?

**Comment by rinnocenti** [comment]
Yes the error happens with characters with linked actors

**Comment by PepijnMC** [comment]
Thanks for the report. Should be fixed in v1.4.1!
